[package]
name = "game101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.18.0"
specs-derive = "0.4.1"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]
